### ISSUE TITLE
Error while starting the app locally

### ISSUE THREAD

**Issue by Starli0n** [heroku/go-getting-started#1]
Hi, 

I was following the tutorial and I am blocked at the step **Run the app locally**

https://devcenter.heroku.com/articles/getting-started-with-go#run-the-app-locally

```
c:\Go\src\github.com\heroku\go-getting-started>foreman start web
17:09:02 web.1  | unknown command: go-getting-started
```

It might be a common mistake but I do not know what to do...

**Comment by thelazyenginerd** [comment]
+1. Getting the same issue on Ubuntu.  I found the executable in the `cmd` directory, but wasn't sure how to get foreman to read it.  Thoughts?

**Comment by JanSichula** [comment]
Hello,

I have exactly the same behavior on Windows. It seems that foreman is not able to properly locate code for go-getting-started which is located in cmd directory. I think it will good to contact Heroku support.

**Comment by freeformz** [comment]
Sorry about this. I'm not sure the best way to handle it.

The [prepare the app step ](https://devcenter.heroku.com/articles/getting-started-with-go#prepare-the-app) includes instructions to add $GOPATH to your $PATH.

```term
$ export PATH=$GOPATH/bin:$PATH
```

If that's been run in the terminal window (for OSX/Linux anyway) the command should be found by foreman. I recommend adding the above snippet to your .bash_profile / .bashrc files if you are doing a bunch of go programming.

Re: MS Windows: Everything is a little different there. I'm (slowly) auditing the docs with a Windows VM and figuring out what the right things are there. In the meantime here is a link to a website that explains how to set environment variables on the various versions of Windows: http://www.computerhope.com/issues/ch000549.htm

I hope this helps

**Comment by freeformz** [comment]
After re-reading I promoted that snippet to one of the items in the Introduction checklist, which makes it more readily noticeable.

**Comment by freeformz** [comment]
@Starli0n @thelazyenginerd @JanSichula do the last 2 comments help you?

**Comment by adrianmacneil** [comment]
This might be obvious, but did you run `godep go build` first?

**Comment by freeformz** [comment]
@adrianmacneil the examples are specifically designed to not require the use of godep for building.

**Comment by freeformz** [comment]
But if you didn't issue a `go install ./...` (from the downloaded source code) or `go install github.com/heroku/go-getting-started/...`) (the ... is important), the commands will not be available in your path anyway.

**Comment by freeformz** [comment]
I'm going to close this as I feel that the correction made to the docs and this discussion should cover the issues. If I am wrong please re-open and provide more info.

Thanks!

**Comment by lokitold** [comment]
From want run heroku local :

1. `go build`
2.  `sudo mv go-getting-started /usr/local/bin/`
 Now if you can run local heroku and run without showing the error
3. `heroku local`

**Comment by robksawyer** [comment]
@lokitold If you have your $GOPATH set correctly, there's no need to move the binary to the `/usr/local/bin` folder. You should just be able to run `heroku local` after step 1 is complete.

**Comment by freeformz** [comment]
`go install` will install the binary into $GOPATH/bin, which I generally recommend people put in their path. So I always suggest people use `go install` over `go build` unless they really want a local binary.

**Comment by mredigonda** [comment]
Running `go build` creates the executable file, but in the current directory. The heroku guide says that you have to run:
1. `go build -o bin/go-getting-started -v .`
2. `heroku local`
Which in my opinion seems a little unconvenient (one would expect for `heroku local` to do everything), but I guess I can set up a script do to that.

**Comment by anacrolix** [comment]
Perhaps this should be re-opened? Running with `$ heroku local` doesn't find the Go binary. That seems wrong.
