### ISSUE TITLE
Can't Push to Heroku Master

### ISSUE THREAD

**Issue by SwanHub** [heroku/go-getting-started#13]
Hi I'm attempting to push to heroku master and am unable to do so. Here is the error I run into: 

`-----> Running: go install -v -tags heroku -mod=vendor github.com/heroku/go-getting-started 
remote: build github.com/heroku/go-getting-started: cannot load github.com/russross/blackfriday: open /tmp/build_2941e2439393141fef10a7281ac13d79/vendor/github.com/russross/blackfriday: no such file or directory

remote:  !     Push rejected, failed to compile Go app.`

Any ideas of what this could be? Thank you in advance.

**Comment by freeformz** [comment]
Two options:

1. Run `go mod vendor` and commit the updated `vendor/` directory.
2. Remove the `vendor` directory and commit the removal.


Basically, when `vendor/` exists the buildpack adds `-mod=vendor` to the `go install` command. The error is telling you that `github.com/russross/blackfriday` can't be found in vendor.

**Comment by freeformz** [comment]
Let me know how that turns out for you.

**Comment by SwanHub** [comment]
Excellent. Thank you. I'm doing some reading on my own, but definitely curious what you know to be the repercussions of deleting the vendor file? Thanks again for your help.

**Comment by freeformz** [comment]
@SwanHub when the vendor directory is up-to-date the go tooling has *all* the code already locally so doesn't need to use the network to fetch any dependencies. When there is no vendor directory dependencies need to be fetched over the network. That can lead to a few different failure scenarios during build.
